### ISSUE TITLE
Support API v2.0 beta

### ISSUE THREAD

**Issue by ankurk91** [ankurk91/bandwidth-notification-channel#8]
Add support for API v2.0
https://dev.bandwidth.com/v2-messaging/

### ToDos
* [x] Add support for API version 2.0 (however it is in beta)
* [x] Mention both versions in readme.
* [x] Introduce new config `applicationId` that will be send in payload
     - [x] Mention that this is required when API version is 2
* [x] Mention `to` can be an array now.
